#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ergo
Version  : 0.3.0
Release  : 4
URL      : https://rubygems.org/downloads/ergo-0.3.0.gem
Source0  : https://rubygems.org/downloads/ergo-0.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-ergo-bin
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-detroit
BuildRequires : rubygem-mast
BuildRequires : rubygem-notify
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# Ergo ç±
[Homepage](http://rubyworks.github.com/ergo) /
[Report Issue](http://github.com/rubyworks/ergo/issues) /
[Source Code](http://github.com/rubyworks/ergo) /
[IRC Channel](http://chat.us.freenode.net/rubyworks)

%package bin
Summary: bin components for the rubygem-ergo package.
Group: Binaries

%description bin
bin components for the rubygem-ergo package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ergo-0.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-ergo.gemspec

%build
gem build rubygem-ergo.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ergo-0.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ergo-0.3.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Array/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Array/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Array/and_without_t-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Array/or_without_t-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Boolean/cdesc-Boolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/bookmark-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/cdesc-Book.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/clear_rule_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/desc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/get_rule_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/import-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/mark-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/notify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/private-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/rule-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/scripts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/state%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Book/states-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/cli_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/debug%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/debug%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/ensure_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/fire%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/fire%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/fire-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/fresh%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/fresh%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/init_project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/print_rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/runner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/script%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/CLI/watch%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/cdesc-Digest.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/checksum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/clear_digests-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/latest-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/refresh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/remove_digest-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/saved-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Digest/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/FileState/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/FileState/cdesc-FileState.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/FileState/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/FileState/pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/cdesc-Ignore.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/concat-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/fnmatch%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/load_ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Ignore/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Match/cdesc-Match.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Match/intialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Match/matchdata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/bookmark%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/bookmarks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/cdesc-Rule.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/desc%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/invoke-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/mark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/mark%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/private%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/private%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/state%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/to_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Rule/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/RootError/cdesc-RootError.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/autorun-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/cdesc-Runner.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/clear_digests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/digests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/fresh%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/fresh%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/fresh_digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/home-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/ignore%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/latest_digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/monorun-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/root%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/root%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/run_bookmarks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/run_rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/save_digests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/script-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/trial%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/trial%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/watch%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/Runner/watch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/ShellUtils/cdesc-ShellUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/ShellUtils/directory%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/ShellUtils/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/ShellUtils/sh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/ShellUtils/sync-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/cdesc-State.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/State/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/System/book-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/System/books-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/System/cdesc-System.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/System/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Ergo/cdesc-Ergo.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/Kernel/cli-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/TrueClass/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/TrueClass/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/TrueClass/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ergo-0.3.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/.index
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/bin/ergo
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/demo/03_runner/01_applying_rules.md
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/demo/applique/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/demo/applique/ergo.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/demo/overview.md
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo.yml
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/book.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/core_ext/boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/core_ext/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/core_ext/true_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/digest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/ignore.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/match.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/rule.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/runner.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/shellutils.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/state.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/lib/ergo/system.rb
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/man/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/man/ergo.1
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/man/ergo.1.html
/usr/lib64/ruby/gems/2.2.0/gems/ergo-0.3.0/man/ergo.1.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/ergo-0.3.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/ergo
